## Read in merged CSV files

In [41]:
import pandas as pd
import numpy as np

pres_data = pd.read_csv('MergedMassData.csv')

gov_data = pd.read_csv('MergedMassDataGov.csv')

In [42]:
pres_data.columns

Index(['STATEFP10', 'COUNTYFP10', 'TRACTCE10', 'GEOID10', 'NAME10',
       'NAMELSAD10', 'MTFCC10', 'ALAND10', 'AWATER10', 'INTPTLAT10',
       'INTPTLON10', 'AREA_SQFT', 'AREA_ACRES_left', 'POP100_RE', 'HU100_RE',
       'LOGPL94171', 'LOGSF1', 'LOGACS0610', 'LOGSF1C', 'SHAPE_AREA_left',
       'SHAPE_LEN_left', 'geometry', 'Tract', '% Point Change in LatinX Pop.',
       '% Point Change in Total Pop.', '% Point Puerto Rican Change',
       '% Point Mexican Change', '% Point Cuban Change',
       '% Point Other LatinX Change', 'Total Population 2016',
       'LatinX Population 2016', 'Mexican 2016', 'Puerto Rican 2016',
       'Cuban 2016', 'Other LatinX 2016', 'Total Population 2019',
       'LatinX Population 2019', 'Mexican 2019', 'Puerto Rican 2019',
       'Cuban 2019', 'Other LatinX 2019', 'index_right', 'WP_NAME', 'WARD',
       'PRECINCT', 'DISTRICT', 'POP_2010', 'TOWN', 'TOWN_ID', 'AREA_SQMI',
       'AREA_ACRES_right', 'YEAR', 'SHAPE_AREA_right', 'SHAPE_LEN_right',
       'City/Town', 'Pct', 'Ward', 'Democratic 2016', 'Republican 2016',
       'Total Votes Cast', 'Democratic 2020', 'Republican 2020',
       'Total Votes Cast 2020', '% Point Change in Democratic Votes',
       '% Change in Total Votes', '% Point Change in Republican Votes'],
      dtype='object')

In [43]:
pres_city = pres_data[['Tract', 'Total Population 2016', 'LatinX Population 2016',
       'Mexican 2016', 'Puerto Rican 2016', 'Cuban 2016', 'Other LatinX 2016',
       'Total Population 2019', 'LatinX Population 2019', 'Mexican 2019',
       'Puerto Rican 2019', 'Cuban 2019', 'Other LatinX 2019', 'City/Town',
       'Democratic 2016', 'Republican 2016', 'Total Votes Cast',
       'Democratic 2020', 'Republican 2020', 'Total Votes Cast 2020']]

In [44]:
#convert Tract column to type str

pres_city['Tract'] = pres_city['Tract'].astype(str)

<ipython-input-44-c73455691d62>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pres_city['Tract'] = pres_city['Tract'].astype(str)

In [45]:
pres_city.dtypes

Tract                      object
Total Population 2016       int64
LatinX Population 2016      int64
Mexican 2016                int64
Puerto Rican 2016           int64
Cuban 2016                  int64
Other LatinX 2016           int64
Total Population 2019       int64
LatinX Population 2019      int64
Mexican 2019                int64
Puerto Rican 2019           int64
Cuban 2019                  int64
Other LatinX 2019           int64
City/Town                  object
Democratic 2016           float64
Republican 2016           float64
Total Votes Cast          float64
Democratic 2020           float64
Republican 2020           float64
Total Votes Cast 2020     float64
dtype: object

In [46]:
#Drop Tract Duplicates 
pres_city = pres_city.drop_duplicates(['Tract'])

#Sum up rows by Town 
pres_city = pres_city.groupby('City/Town').sum()

## Add columns with percent change

In [47]:
pres_city['% LatinX 2016'] = pres_city['LatinX Population 2016']/pres_city['Total Population 2016']

pres_city['% LatinX 2019'] = pres_city['LatinX Population 2019']/pres_city['Total Population 2019']


pres_city = pres_city.rename(columns = {'Total Votes Cast':'Total Votes Cast 2016'})


pres_city['% Democratic 2016'] = pres_city['Democratic 2016']/pres_city['Total Votes Cast 2016']

pres_city['% Democratic 2020'] = pres_city['Democratic 2020']/pres_city['Total Votes Cast 2020']


pres_city['% Republican 2016'] = pres_city['Republican 2016']/pres_city['Total Votes Cast 2016']

pres_city['% Republican 2020'] = pres_city['Republican 2020']/pres_city['Total Votes Cast 2020']

## Add columns with percentage point change

In [111]:
pres_city['Democratic Percentage point Change'] = (pres_city['% Democratic 2020'] - pres_city['% Democratic 2016'])*100

pres_city['Republican Percentage point Change'] = (pres_city['% Republican 2020'] - pres_city['% Republican 2016'])*100

pres_city['Change LatinX'] = (pres_city['% LatinX 2019'] - pres_city['% LatinX 2016'])*100

In [112]:
pres_city.head()

,Total Population 2016,LatinX Population 2016,Mexican 2016,Puerto Rican 2016,Cuban 2016,Other LatinX 2016,Total Population 2019,LatinX Population 2019,Mexican 2019,Puerto Rican 2019,...,Total Votes Cast 2020,% LatinX 2016,% LatinX 2019,% Democratic 2016,% Democratic 2020,% Republican 2016,% Republican 2020,Democratic Percentage point Change,Republican Percentage point Change,Change LatinX
City/Town,,,,,,,,,,,,,,,,,,,,,
ABINGTON,16586,361,63,157,0,141,17908,342,98,60,...,5553.0,0.021765,0.019098,0.444159,0.517558,0.469219,0.454529,7.339864,-1.468954,-0.266773
ACTON,18514,292,27,47,19,199,19437,709,19,102,...,9784.0,0.015772,0.036477,0.711616,0.794665,0.195389,0.175797,8.304882,-1.959222,2.070497
ACUSHNET,7589,245,13,140,51,41,7718,321,11,194,...,3961.0,0.032284,0.041591,0.442919,0.437263,0.482229,0.533704,-0.565537,5.147421,0.930752
ADAMS,7258,189,16,112,0,61,6748,350,68,218,...,2809.0,0.026040,0.051867,0.617761,0.666429,0.289961,0.302955,4.866872,1.299340,2.582699
AGAWAM,48369,5396,115,4611,111,559,48276,5607,227,4945,...,18782.0,0.111559,0.116145,0.423589,0.485412,0.495315,0.489990,6.182295,-0.532425,0.458561

In [113]:
#Find Towns where the LatinX pop was greater than 30% in 2016
towns_LatinX_2016 = pres_city.loc[(pres_city['% LatinX 2016'] >= .30)]

In [114]:
towns_LatinX_2016.shape

(6, 27)

In [115]:
towns_LatinX_2016

,Total Population 2016,LatinX Population 2016,Mexican 2016,Puerto Rican 2016,Cuban 2016,Other LatinX 2016,Total Population 2019,LatinX Population 2019,Mexican 2019,Puerto Rican 2019,...,Total Votes Cast 2020,% LatinX 2016,% LatinX 2019,% Democratic 2016,% Democratic 2020,% Republican 2016,% Republican 2020,Democratic Percentage point Change,Republican Percentage point Change,Change LatinX
City/Town,,,,,,,,,,,,,,,,,,,,,
CHELSEA,52441,27712,787,4599,217,22109,54565,31645,1299,4502,...,7131.0,0.528441,0.579951,0.734743,0.766092,0.166442,0.206984,3.134887,4.054185,5.150903
HOLYOKE,45058,16675,111,15439,41,1084,45343,18404,217,16586,...,13320.0,0.370079,0.405884,0.673746,0.657583,0.248525,0.314715,-1.616373,6.618964,3.580547
LAWRENCE,67102,48596,297,13146,447,34706,67842,50706,440,12501,...,15104.0,0.724211,0.747413,0.838300,0.734044,0.116767,0.242386,-10.425567,12.561895,2.320220
LYNN,102991,34226,1600,5379,155,27092,103603,38091,1839,3930,...,28753.0,0.332320,0.367663,0.686249,0.701040,0.237044,0.275728,1.479136,3.868417,3.534280
METHUEN,62471,21879,275,7071,173,14360,64852,25768,255,6979,...,26881.0,0.350227,0.397335,0.535401,0.576615,0.391613,0.399353,4.121485,0.773999,4.710897
SPRINGFIELD,167915,62062,2538,51688,273,7563,167224,67004,2087,56767,...,33729.0,0.369604,0.400684,0.728685,0.697975,0.208310,0.256278,-3.071012,4.796808,3.108044

## See which of those towns had majority Republican support

In [116]:
towns_LatinX_2016 = towns_LatinX_2016.loc[(towns_LatinX_2016['% Republican 2016'] > towns_LatinX_2016['% Democratic 2016'])]

In [117]:
towns_LatinX_2016.shape

(0, 27)

In [118]:
towns_LatinX_2019 = pres_city.loc[(pres_city['% LatinX 2019'] >= .30)]

In [119]:
towns_LatinX_2019.head()

,Total Population 2016,LatinX Population 2016,Mexican 2016,Puerto Rican 2016,Cuban 2016,Other LatinX 2016,Total Population 2019,LatinX Population 2019,Mexican 2019,Puerto Rican 2019,...,Total Votes Cast 2020,% LatinX 2016,% LatinX 2019,% Democratic 2016,% Democratic 2020,% Republican 2016,% Republican 2020,Democratic Percentage point Change,Republican Percentage point Change,Change LatinX
City/Town,,,,,,,,,,,,,,,,,,,,,
CHELSEA,52441,27712,787,4599,217,22109,54565,31645,1299,4502,...,7131.0,0.528441,0.579951,0.734743,0.766092,0.166442,0.206984,3.134887,4.054185,5.150903
HOLYOKE,45058,16675,111,15439,41,1084,45343,18404,217,16586,...,13320.0,0.370079,0.405884,0.673746,0.657583,0.248525,0.314715,-1.616373,6.618964,3.580547
LAWRENCE,67102,48596,297,13146,447,34706,67842,50706,440,12501,...,15104.0,0.724211,0.747413,0.838300,0.734044,0.116767,0.242386,-10.425567,12.561895,2.320220
LYNN,102991,34226,1600,5379,155,27092,103603,38091,1839,3930,...,28753.0,0.332320,0.367663,0.686249,0.701040,0.237044,0.275728,1.479136,3.868417,3.534280
METHUEN,62471,21879,275,7071,173,14360,64852,25768,255,6979,...,26881.0,0.350227,0.397335,0.535401,0.576615,0.391613,0.399353,4.121485,0.773999,4.710897

In [120]:
towns_LatinX_2019.shape

(6, 27)

In [121]:
#Find Towns where the LatinX pop was greater than 10 in 2016%
towns_10_2016 = pres_city.loc[(pres_city['% LatinX 2016'] >= .10)]

In [122]:
towns_10_2016.shape

(39, 27)

In [123]:
towns_10_2016 = towns_10_2016.loc[(towns_10_2016['% Republican 2016'] > towns_10_2016['% Democratic 2016'])]

In [124]:
towns_10_2016.shape

(6, 27)

In [125]:
towns_10_2016

,Total Population 2016,LatinX Population 2016,Mexican 2016,Puerto Rican 2016,Cuban 2016,Other LatinX 2016,Total Population 2019,LatinX Population 2019,Mexican 2019,Puerto Rican 2019,...,Total Votes Cast 2020,% LatinX 2016,% LatinX 2019,% Democratic 2016,% Democratic 2020,% Republican 2016,% Republican 2020,Democratic Percentage point Change,Republican Percentage point Change,Change LatinX
City/Town,,,,,,,,,,,,,,,,,,,,,
AGAWAM,48369,5396,115,4611,111,559,48276,5607,227,4945,...,18782.0,0.111559,0.116145,0.423589,0.485412,0.495315,0.489990,6.182295,-0.532425,0.458561
FREETOWN,4047,417,0,231,0,186,3802,363,0,136,...,1856.0,0.103039,0.095476,0.415150,0.444504,0.513799,0.534483,2.935457,2.068358,-0.756322
LEICESTER,7215,764,5,552,8,199,7103,471,0,251,...,3277.0,0.105891,0.066310,0.421634,0.476350,0.483590,0.490693,5.471603,0.710262,-3.958050
MILLBURY,22845,2571,1,1784,47,739,22628,2712,49,2000,...,10747.0,0.112541,0.119852,0.428456,0.498372,0.485407,0.466642,6.991602,-1.876552,0.731047
STERLING,26863,2886,52,1663,11,1160,27086,3526,107,2199,...,13625.0,0.107434,0.130178,0.429787,0.518165,0.456186,0.444917,8.837824,-1.126896,2.274393
WILBRAHAM,24087,4880,345,4111,36,388,23480,4486,300,3667,...,12008.0,0.202599,0.191056,0.442097,0.527898,0.463689,0.444953,8.580155,-1.873585,-1.154269

In [126]:
#Find Towns where the LatinX pop was greater than 10% in 2019
towns_10_2019 = pres_city.loc[(pres_city['% LatinX 2019'] >= .10)]

In [127]:
towns_10_2019.shape

(36, 27)

In [128]:
towns_10_2019 = towns_10_2019.loc[(towns_10_2019['% Republican 2020'] > towns_10_2019['% Democratic 2020'])]

In [129]:
towns_10_2019

,Total Population 2016,LatinX Population 2016,Mexican 2016,Puerto Rican 2016,Cuban 2016,Other LatinX 2016,Total Population 2019,LatinX Population 2019,Mexican 2019,Puerto Rican 2019,...,Total Votes Cast 2020,% LatinX 2016,% LatinX 2019,% Democratic 2016,% Democratic 2020,% Republican 2016,% Republican 2020,Democratic Percentage point Change,Republican Percentage point Change,Change LatinX
City/Town,,,,,,,,,,,,,,,,,,,,,
AGAWAM,48369,5396,115,4611,111,559,48276,5607,227,4945,...,18782.0,0.111559,0.116145,0.423589,0.485412,0.495315,0.48999,6.182295,-0.532425,0.458561

In [130]:
#Find Towns 2016 where the LatinX pop is greater than 15%
towns_15_2016 = pres_city.loc[(pres_city['% LatinX 2016'] >= .15)]

In [131]:
towns_15_2016.shape

(23, 27)

In [132]:
towns_15_2016 = towns_15_2016.loc[(towns_15_2016['% Republican 2016'] > towns_15_2016['% Democratic 2016'])]

In [133]:
towns_15_2016

,Total Population 2016,LatinX Population 2016,Mexican 2016,Puerto Rican 2016,Cuban 2016,Other LatinX 2016,Total Population 2019,LatinX Population 2019,Mexican 2019,Puerto Rican 2019,...,Total Votes Cast 2020,% LatinX 2016,% LatinX 2019,% Democratic 2016,% Democratic 2020,% Republican 2016,% Republican 2020,Democratic Percentage point Change,Republican Percentage point Change,Change LatinX
City/Town,,,,,,,,,,,,,,,,,,,,,
WILBRAHAM,24087,4880,345,4111,36,388,23480,4486,300,3667,...,12008.0,0.202599,0.191056,0.442097,0.527898,0.463689,0.444953,8.580155,-1.873585,-1.154269

In [134]:
towns_15_2019 = pres_city.loc[(pres_city['% LatinX 2019'] >= .15)]

In [135]:
towns_15_2019.shape

(25, 27)

In [136]:
towns_15_2019 = towns_15_2019.loc[(towns_15_2019['% Republican 2020'] > towns_15_2019['% Democratic 2020'])]

In [137]:
towns_15_2019.shape

(0, 27)

## Top 10 Towns with the highest LatinX Percentage

In [138]:
#Top 10 Towns with the highest LatinX Percentage

largest_LatinX = pres_city.nlargest(10, ['% LatinX 2019', 'Republican Percentage point Change'])

In [139]:
largest_LatinX

,Total Population 2016,LatinX Population 2016,Mexican 2016,Puerto Rican 2016,Cuban 2016,Other LatinX 2016,Total Population 2019,LatinX Population 2019,Mexican 2019,Puerto Rican 2019,...,Total Votes Cast 2020,% LatinX 2016,% LatinX 2019,% Democratic 2016,% Democratic 2020,% Republican 2016,% Republican 2020,Democratic Percentage point Change,Republican Percentage point Change,Change LatinX
City/Town,,,,,,,,,,,,,,,,,,,,,
LAWRENCE,67102,48596,297,13146,447,34706,67842,50706,440,12501,...,15104.0,0.724211,0.747413,0.838300,0.734044,0.116767,0.242386,-10.425567,12.561895,2.320220
CHELSEA,52441,27712,787,4599,217,22109,54565,31645,1299,4502,...,7131.0,0.528441,0.579951,0.734743,0.766092,0.166442,0.206984,3.134887,4.054185,5.150903
HOLYOKE,45058,16675,111,15439,41,1084,45343,18404,217,16586,...,13320.0,0.370079,0.405884,0.673746,0.657583,0.248525,0.314715,-1.616373,6.618964,3.580547
SPRINGFIELD,167915,62062,2538,51688,273,7563,167224,67004,2087,56767,...,33729.0,0.369604,0.400684,0.728685,0.697975,0.208310,0.256278,-3.071012,4.796808,3.108044
METHUEN,62471,21879,275,7071,173,14360,64852,25768,255,6979,...,26881.0,0.350227,0.397335,0.535401,0.576615,0.391613,0.399353,4.121485,0.773999,4.710897
LYNN,102991,34226,1600,5379,155,27092,103603,38091,1839,3930,...,28753.0,0.332320,0.367663,0.686249,0.701040,0.237044,0.275728,1.479136,3.868417,3.534280
EVERETT,39641,9394,202,1166,53,7973,40852,11215,224,1620,...,9545.0,0.236977,0.274528,0.657777,0.692300,0.286432,0.286118,3.452235,-0.031321,3.755070
REVERE,46091,11178,641,1279,83,9175,45426,12432,542,1862,...,7643.0,0.242520,0.273676,0.568050,0.599764,0.362517,0.374068,3.171470,1.155049,3.115564
FITCHBURG,44974,10155,853,6710,34,2558,46329,11950,1060,8446,...,15794.0,0.225797,0.257938,0.561271,0.601051,0.345195,0.369634,3.977992,2.443880,3.214067
SHERBORN,24450,6091,576,2225,11,3279,25212,5860,349,2223,...,14955.0,0.249121,0.232429,0.648549,0.757940,0.226588,0.193581,10.939109,-3.300758,-1.669165

In [140]:
insight = pres_city.nlargest(5, ['% LatinX 2019', 'Republican Percentage point Change'])

insight = insight[['% LatinX 2019', 'Democratic Percentage point Change', 'Republican Percentage point Change']]

In [141]:
insight

,% LatinX 2019,Democratic Percentage point Change,Republican Percentage point Change
City/Town,,,
LAWRENCE,0.747413,-10.425567,12.561895
CHELSEA,0.579951,3.134887,4.054185
HOLYOKE,0.405884,-1.616373,6.618964
SPRINGFIELD,0.400684,-3.071012,4.796808
METHUEN,0.397335,4.121485,0.773999

## Percentage of cities that saw an increase in the LatinX pop from 2016-2019

In [142]:
#percent of cities that saw an increase in the LatinX pop from 2016-2019

increase = pres_city[(pres_city['Change LatinX']) > 0].count()[0] / pres_city.shape[0]

decrease = 1 - increase 

print("Increase =", increase)
print("Decrease =", decrease)

Increase = 0.73828125
Decrease = 0.26171875

In [143]:
#avg LatinX Percentage change for all Towns in MA
pres_city['Change LatinX'].mean()

0.75259252143844

In [144]:
#avg Percentage change in Republican Support for all Towns in MA
pres_city['Republican Percentage point Change'].mean()

-0.9359053731964311

## Percent of cities that saw an increase in the Republican Support from 2016-2019

In [145]:
increase = pres_city[(pres_city['Republican Percentage point Change']) > 0].count()[0] / pres_city.shape[0]

decrease = 1 - increase 

print("Increase =", increase)
print("Decrease =", decrease)

Increase = 0.2421875
Decrease = 0.7578125

In [153]:
#Find top 10 Cities with the Largest Republican Percentage point changes from 2016-2020
largest_republican = pres_city.nlargest(10, ['Republican Percentage point Change'])

largest_republican = largest_republican[['Republican Percentage point Change']]

largest_republican

             Republican Percentage point Change
City/Town
LAWRENCE                              12.561895
FALL RIVER                             8.684897
NEW BEDFORD                            6.656434
HOLYOKE                                6.618964
FLORIDA                                5.833333
ACUSHNET                               5.147421
WINDSOR                                4.931346
SPRINGFIELD                            4.796808
CHELSEA                                4.054185
LYNN                                   3.868417

In [152]:
#Find top 10 Cities with the Largest Democratic Percentage point changes from 2016-2020
largest_democratic = pres_city.nlargest(10, ['Democratic Percentage point Change'])

largest_democratic = largest_democratic[['Democratic Percentage point Change']]

largest_democratic

              Democratic Percentage point Change
City/Town
NORTHBRIDGE                            11.818252
DOVER                                  11.756075
SOUTHBOROUGH                           11.677676
WENHAM                                 11.322334
WENDELL                                11.038137
NORFOLK                                10.987656
SHERBORN                               10.939109
MILLIS                                 10.881055
HAMILTON                               10.804285
STOW                                   10.710509

In [151]:
#Find top 10 Cities with the largest LatinX percentage point increase from 2016-2020

largest_latinx_change = pres_city.nlargest(10, ['Change LatinX'])

largest_latinx_change = largest_latinx_change[['Change LatinX']]

largest_latinx_change

            Change LatinX
City/Town
HOPEDALE         6.594522
DUDLEY           6.530052
CHELSEA          5.150903
METHUEN          4.710897
SAUGUS           4.630230
RICHMOND         4.151074
SOMERVILLE       4.147313
ASHLAND          3.952907
RUTLAND          3.925956
WALPOLE          3.917325

In [ ]:
#Latino pop shift overall

latinx_2016 = pres_city['LatinX Population 2016'].sum()

latinx_2019 = pres_city['LatinX Population 2019'].sum()


#total LatinX percentage increase in MA from 2016-2019
latinx_change = (latinx_2019 - latinx_2016) / latinx_2016

print(latinx_change*100)

total_pop_2016 = pres_city['Total Population 2016'].sum()

total_pop_2019 = pres_city['Total Population 2019'].sum()



latinx_percentage_2016 = latinx_2016/total_pop_2016

latinx_percentage_2019 = latinx_2019/total_pop_2019



#total LatinX percentage point increase in MA from 2016-2019
total_latinX_change = (latinx_percentage_2019 * 100) - (latinx_percentage_2016 * 100)

In [ ]:
#Percentage point change in Democratic support in MA as a whole from 2016-2020

Democratic_2016 = pres_city['Democratic 2016'].sum()

Democratic_2020 = pres_city['Democratic 2020'].sum()

total_votes_2016 = pres_city['Total Votes Cast 2016'].sum()

total_votes_2020 = pres_city['Total Votes Cast 2020'].sum()


Democratic_percentage_2016 = Democratic_2016/total_votes_2016

Democratic_percentage_2020 = Democratic_2020/total_votes_2020


#total Democratic percentage point change in MA from 2016-2019

total_democratic_change = (Democratic_percentage_2020*100) - (Democratic_percentage_2016*100)

print(total_democratic_change)

In [ ]:
#Percentage point change in Republican support in MA as a whole from 2016-2020


Republican_2016 = pres_city['Republican 2016'].sum()

Republican_2020 = pres_city['Republican 2020'].sum()

total_votes_2016 = pres_city['Total Votes Cast 2016'].sum()

total_votes_2020 = pres_city['Total Votes Cast 2020'].sum()


Republican_percentage_2016 = Republican_2016/total_votes_2016

Republican_percentage_2020 = Republican_2020/total_votes_2020


#total Democratic percentage point change in MA from 2016-2019

total_republican_change = (Republican_percentage_2020*100) - (Republican_percentage_2016*100)

print(total_republican_change)